cloud: AWS

UDP:
  enable: True # True/False
  ip: "0.0.0.0"
  port: 4114

COAP:
  enable: True  # True/False
  ip: "0.0.0.0"
  port: 5683

KITE:
  url: "https://m2m-api.telefonica.com:8010"
  apn: "m2m.movistar.es"
  certificate: "cer_file" # certificate file name
  private_key: "key_file" # key file name

location: True
cloudlog: True

